### ISSUE TITLE
Add proxy/redirect option

### ISSUE THREAD

**Issue by JosuaKrause** [VisTrails/tej#18]
Add a way to pass a list of servers that have to be visited prior to the final server.
Eg. in the destination parameter add a field "proxy" that contains a list of intermediate steps that need to be visited before accessing the final server. This is useful in the context of VPN networks where you need to access a VPN entry server from which you can access the actual server.

**Comment by JosuaKrause** [comment]
Kind of like:
```
ssh -L11111:finalhost:22 user@middlehost
```
and
```
ssh -p 11111 user@localhost
```

**Comment by remram44** [comment]
Implementing the tunneling in Python with paramiko would add quite a bit of code 😭 And people usually establish the tunnel or VPN once, outside of the each tool they use.

So this is possible but I don't want to 😳
