### ISSUE TITLE
First job creation always fails

### ISSUE THREAD

**Issue by JosuaKrause** [VisTrails/tej#21]
Not sure if my setup only but the first job I create always gets stuck in the `created` phase and crashes the `new_job` script (resulting in `JobNotFound("Couldn't create job")` on the python side).

Might have to do with the unused line
https://github.com/VisTrails/tej/blob/master/tej/remotes/default/commands/new_job#L40

Subsequent job creations work without any problem and execute properly.

**Comment by remram44** [comment]
The only thing different between the first job and the next ones is that the runtime gets installed. But I never encountered that on my test machines (or Travis).

**Comment by remram44** [comment]
That line is left over from 31041b83 when I changed new_job to not create the "stage" subdirectory, which makes it easier to scp a directory to the server (adb887f7). I'll remove it, but I don't think that will change anything.

**Comment by remram44** [comment]
I think tej cannot resolve a relative queue path before it exists. I only test with absolute paths (starting with `~/`). Resolving it once it exists works, hence the subsequent submits work. I will fix it.

**Comment by JosuaKrause** [comment]
I changed my tej-path to absolute and it works now. Thanks!

**Comment by remram44** [comment]
06bf1521 should have fixed all this.
