### ISSUE TITLE
Provide way to clean up server

### ISSUE THREAD

**Issue by JosuaKrause** [VisTrails/tej#27]
Provide method that removes the tej directory from the server. Right now there is no clean way of uninstalling tej if it is no longer in need. A workaround is `check_call('rm -rf ' + TEJ_DIR)` which is not very safe or logging on to the server, locating the directory, and deleting it.

**Comment by JosuaKrause** [comment]
Example of work-around: https://github.com/JosuaKrause/parcell/blob/8d51c79040cbc3e878e37b04af0412ba3e91d982/parcell/loading.py#L626--L631

**Comment by remram44** [comment]
It's not clear to me why you'd want to do that. Most programs leave cache files behind, deleting (killing?) all the jobs should be enough. There is also a race condition removing the queue.

**Comment by JosuaKrause** [comment]
I currently avoid the race condition by allowing only one instance (external lock) and one thread (internal lock) to do destructive operations. You could offer a server side method that attempts to kill all jobs and advise the user to ensure that there is no race condition (not sure of a more user friendly solution).

However, leaving files behind is a quite unclean solution. Do you have an example of a program that doesn't properly uninstall itself when ask to do so?

**Comment by remram44** [comment]
I feel like every program that creates dot files leaves then behind when uninstalled...

**Comment by JosuaKrause** [comment]
Okay, true. However, what is your suggestion for updating?

**Comment by JosuaKrause** [comment]
Actually, you're leaving a dot file on the *server* where tej is not even installed.

**Comment by remram44** [comment]
Update is indeed an issue... I have version numbers, but no real way of updating right now (and I would need some lock file to do this safely). I'll merge #29 once I'm confident it works.
